import { FeedItem, Course, UserStats, Badge } from './types';

export const MOCK_FEED: FeedItem[] = [
  {
    id: '7',
    type: 'video',
    subject: 'physics',
    title: 'Chute Libre',
    content: 'Analyse d\'un mouvement de chute libre sans frottements.',
    author: 'SciencesXpert',
    likes: 15,
    videoUrl: 'https://res.cloudinary.com/drkb0wvcj/video/upload/chuteLibre_dmlk72.mp4',
  },
  {
    id: '8',
    type: 'video',
    subject: 'physics',
    title: 'Ascenseur',
    content: 'Comprendre les forces en jeu dans un ascenseur en mouvement.',
    author: 'SciencesXpert',
    likes: 25,
    videoUrl: 'https://res.cloudinary.com/drkb0wvcj/video/upload/ascenceur_tiktok_zhfbvj.mp4',
  },
  {
    id: '9',
    type: 'video',
    subject: 'physics',
    title: 'Altitude Géo',
    content: 'Calcul de l\'altitude géopotentielle et ses applications.',
    author: 'SciencesXpert',
    likes: 30,
    videoUrl: 'https://res.cloudinary.com/drkb0wvcj/video/upload/altitudeGeo_z5x7hx.mp4',
  },
  {
    id: '10',
    type: 'carousel',
    subject: 'maths',
    title: 'Exercice & Correction',
    content: 'Un exercice sur les suites et sa correction détaillée. Slide vers la droite pour voir la solution !',
    author: 'SciencesXpert',
    likes: 42,
    images: [
      'https://res.cloudinary.com/drkb0wvcj/image/upload/2_1_eyvcl6.png',
      'https://res.cloudinary.com/drkb0wvcj/image/upload/Tiktok__j_9_xens_1_-3_-by_MaxAI_qifcvi.png'
    ],
  },
  {
    id: '1',
    type: 'video',
    subject: 'maths',
    title: 'La Dérivée Intuitive',
    content: 'Découvre comment la pente d\'une courbe définit la variation instantanée. Un concept clé pour la Terminale S.',
    author: 'SciencesXpert',
    likes: 1240, //Faire en sorte de faire un truc dynamique pour la suite 
    videoUrl: '',
  },
  {
    id: '2',
    type: 'formula',
    subject: 'physics',
    title: 'Relativité Restreinte',
    content: 'E=mc² : L\'énergie est égale à la masse multipliée par le carré de la célérité. Une révolution signée Einstein.',
    author: 'Albert E.',
    likes: 3500,
  },
  {
    id: '3',
    type: 'funfact',
    subject: 'chemistry',
    title: 'L\'Or est Inoxydable',
    content: 'Sais-tu pourquoi l\'or est si précieux ? Sa structure atomique le rend presque totalement insensible à l\'oxydation.',
    author: 'SciencesXpert',
    likes: 890,
  },
  {
    id: '4',
    type: 'method',
    subject: 'maths',
    title: 'Loi Binomiale',
    content: 'Comment calculer la probabilité de k succès parmi n expériences indépendantes. Un must pour le Bac.',
    author: 'SciencesXpert',
    likes: 450,
  },
  {
    id: '5',
    type: 'video',
    subject: 'physics',
    title: 'Les Lois de Kepler',
    content: 'Comprendre le mouvement des planètes autour du Soleil. Les orbites ne sont pas des cercles !',
    author: 'SciencesXpert',
    likes: 1560,
    videoUrl: '',
  },
  {
    id: '6',
    type: 'video',
    subject: 'physics',
    title: 'Pendule Élastique',
    content: 'Étude du mouvement d\'un système masse-ressort. Énergie cinétique et potentielle.',
    author: 'SciencesXpert',
    likes: 2450,  
    videoUrl: '',
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'maths-t',
    subject: 'maths',
    title: 'Mathématiques Terminale',
    chaptersCount: 17,
    exercisesCount: 200,
    progress: 35,
    chapters: [
      { id: 'arithmetique', title: 'Arithmétique', description: 'Division euclidienne, congruences, Bézout, Gauss et nombres premiers.', isCompleted: true, category: 'algebre', icon: '🔢' },
      { id: 'continuité', title: 'Continuité', description: 'Théorème des valeurs intermédiaires, continuité sur un intervalle.', isCompleted: true, category: 'analyse', icon: '📈' },
      { id: 'convexité', title: 'Convexité', description: 'Dérivée seconde, concavité, points d\'inflexion.', isCompleted: true, category: 'analyse', icon: '📈' },
      { id: 'denombrement', title: 'Dénombrement', description: 'Combinaisons, arrangements, permutations et dénombrement d\'ensembles.', isCompleted: true, category: 'algebre', icon: '🔢' },
      { id: 'dérivabilité', title: 'Dérivabilité', description: 'Nombre dérivé, équation de tangente, théorèmes de dérivation.', isCompleted: true, category: 'analyse', icon: '📈' },
      { id: 'equa-diff', title: 'Équations différentielles', description: 'Résolution d\'équations différentielles linéaires d\'ordre 1 et 2.', isCompleted: true, category: 'analyse', icon: '📈' },
      { id: 'limites', title: 'Limites de fonctions', description: 'Étude des limites, asymptotes et continuité graphique.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'suites', title: 'Suites numériques', description: 'Raisonnement par récurrence, limites de suites et comportement asymptotique.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'probabilites', title: 'Probabilités', description: 'Conditionnement, indépendance, lois de probabilités et loi binomiale.', isCompleted: false, category: 'probabilites', icon: '🎲' },
      { id: 'primitives', title: 'Primitives', description: 'Définition, recherche de primitives et lien avec la dérivation.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'integrales', title: 'Intégration', description: 'Calcul intégral, intégration par parties et applications géométriques.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'ln', title: 'Fonction Logarithme', description: 'Propriétés de la fonction ln, étude de fonctions et limites.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'matrices', title: 'Calcul matriciel', description: 'Opérations sur les matrices, systèmes linéaires et applications.', isCompleted: false, category: 'algebre', icon: '🔢' },
      { id: 'exp', title: 'Fonction Exponentielle', description: 'Définition, propriétés algébriques et limites.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'etude-fonctions', title: 'Étude de fonctions', description: 'Limites, variations, asymptotes et convexité.', isCompleted: false, category: 'analyse', icon: '📈' },
      { id: 'geometrie', title: 'Géométrie dans l\'espace', description: 'Vecteurs de l\'espace, droites, plans, produit scalaire.', isCompleted: false, category: 'algebre', icon: '📐' },
      { id: 'trigo', title: 'Trigonométrie', description: 'Formules trigonométriques, fonctions cosinus et sinus.', isCompleted: false, category: 'analyse', icon: '📐' },
    ],
  },
  {
    id: 'phys-t',
    subject: 'physics',
    title: 'Physique Terminale',
    chaptersCount: 16,
    exercisesCount: 150,
    progress: 0,
    chapters: [
      { id: 'effet-doppler', title: 'Effet Doppler', description: 'Décalage de fréquence d\'une onde en mouvement.', isCompleted: false, category: 'ondes', icon: '🔊' },
      { id: 'diffraction', title: 'Diffraction', description: 'Diffraction des ondes à travers une fente ou un obstacle.', isCompleted: false, category: 'ondes', icon: '🌊' },
      { id: 'interferences', title: 'Interférences', description: 'Superposition de deux ondes cohérentes, interférences constructives/destructives.', isCompleted: false, category: 'ondes', icon: '⚡' },
      { id: 'optique', title: 'Optique géométrique', description: 'Lois de Snell-Descartes et propagation de la lumière.', isCompleted: false, category: 'optique', icon: '🔍' },
      { id: 'lentilles', title: 'Lentilles convergentes', description: 'Relation de conjugaison, grandissement et formation d\'images.', isCompleted: false, category: 'optique', icon: '👓' },
      { id: 'lunette', title: 'Lunette astronomique', description: 'Modèle optique afocal d\'une lunette astronomique.', isCompleted: false, category: 'optique', icon: '🔭' },
      { id: 'cinematique', title: 'Cinématique', description: 'Vecteurs position, vitesse et accélération dans différents repères.', isCompleted: false, category: 'mecanique', icon: '🏃' },
      { id: 'dynamique', title: 'Dynamique de Newton', description: 'Les trois lois de Newton et applications au mouvement.', isCompleted: false, category: 'mecanique', icon: '⚖️' },
      { id: 'mecanique', title: 'Mécanique', description: 'Étude dynamique des mouvements plans (projectile, plan incliné).', isCompleted: false, category: 'mecanique', icon: '⚙️' },
      { id: 'celestes', title: 'Mécanique céleste', description: 'Mouvement des satellites et des planètes, lois de Kepler.', isCompleted: false, category: 'mecanique', icon: '🪐' },
      { id: 'energie', title: 'Énergie mécanique', description: 'Énergie cinétique, potentielle et conservation de l\'énergie mécanique.', isCompleted: false, category: 'mecanique', icon: '🔋' },
      { id: 'fluides', title: 'Dynamique des fluides', description: 'Écoulement d\'un fluide physique, relation de Bernoulli.', isCompleted: false, category: 'mecanique', icon: '💧' },
      { id: 'electrocinetique', title: 'Électrocinétique', description: 'Circuits RC, charge et décharge d\'un condensateur.', isCompleted: false, category: 'ondes', icon: '🔌' },
      { id: 'thermo', title: 'Thermodynamique', description: 'Premier principe, transferts thermiques et bilans d\'énergie.', isCompleted: false, category: 'mecanique', icon: '🔥' },
      { id: 'quantique', title: 'Physique quantique', description: 'Dualité onde-particule, quantification de l\'énergie.', isCompleted: false, category: 'ondes', icon: '⚛️' },
      { id: 'incertitudes', title: 'Mesures & Incertitudes', description: 'Évaluation des incertitudes de type A et de type B.', isCompleted: false, category: 'mecanique', icon: '📏' },
    ],
  },
  {
    id: 'chem-t',
    subject: 'chemistry',
    title: 'Chimie Terminale',
    chaptersCount: 10,
    exercisesCount: 120,
    progress: 60,
    chapters: [
      { id: 'c1', title: 'Acides et Bases', description: 'pH, titrage et équilibres.', isCompleted: true, category: 'chimie', icon: '🧪' },
      { id: 'c2', title: 'Cinétique chimique', description: 'Vitesse de réaction et facteurs.', isCompleted: true, category: 'chimie', icon: '🧪' },
    ],
  },
];

export const MOCK_USER_STATS: UserStats = {
  xp: 450,
  level: 12,
  streak: 7,
  summariesRead: 45,
  exercisesSolved: 128,
  favorites: 12,
};

export const MOCK_BADGES: Badge[] = [
  { 
    id: '1', 
    name: 'Test', 
    description: 'test',
    requirement: 'test',
    icon: 'test', 
    isUnlocked: true 
  }
];
